GET  http://127.0.0.1:8000/posts

###
GET http://127.0.0.1:8000/posts/3

###
POST http://127.0.0.1:8000/posts
Content-Type: application/json

{
    "title": "test",
    "body": "test",
    "cid": 1
}

###
PUT  http://127.0.0.1:8000/posts/5
Content-Type: application/json

{
    "title": "test5",
    "body": "test5",
    "cid": 1
}


###
POST http://127.0.0.1:8001/users
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}